# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JDK_VERSION: 8

    steps:
     - name: Checkout
       uses: actions/checkout@v3.5.0

     - name: Cache
       uses: actions/cache@v3.3.1
       with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('pom.xml') }}

     - name: Set JDK
       uses: actions/setup-java@v3.11.0
       with:
         java-version: |
           8
         distribution: 'temurin'
         mvn-toolchain-id: |
           JavaSE-1.8
         server-id: ossrh
         server-username: MAVEN_USERNAME
         server-password: MAVEN_PASSWORD

     - name: Import GPG key
       uses: crazy-max/ghaction-import-gpg@v5.2.0
       with:
         gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
         passphrase: ${{ secrets.GPG_PASSPHRASE }}

     - name: Compile
       run: mvn clean deploy -U -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} -Prelease
       env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

  sonar:
    runs-on: ubuntu-latest
    env:
      JDK_VERSION: 17

    steps:
     - name: Checkout
       uses: actions/checkout@v3.5.0

     - name: Cache
       uses: actions/cache@v3.3.1
       with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('pom.xml') }}

     - name: Set JDK
       uses: actions/setup-java@v3.11.0
       with:
         java-version: |
           17
         distribution: 'temurin'
         mvn-toolchain-id: |
           JavaSE-17

     - name: Compile
       run: mvn clean org.sonarsource.scanner.maven:sonar-maven-plugin:sonar verify -U -Dsonar.organization=b3dgs -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=b3dgs_b3dgs-parent
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

